### PR TITLE
remove redundant "SK" function replaced by Second

### PR DESCRIPTION
**Pull request by a-lipson**
the duplicate function is not implemented

### CODE REVIEW

**Comment by CarstenLeue** [comment]
Hi @a-lipson sorry for the late reply, I was on vacation. This function is the port of https://github.com/gcanti/fp-ts/blob/3.0.0/src/function.ts#L684 from fp-ts.

Why would you suggest to remove it?

**Comment by a-lipson** [comment]
Hi, Dr. Cartsen, no worries; sorry for the late reply.

Initially, I was just thinking about opening an issue to ask this as a question since I didn't look over to the ts library for a matching function;

I saw that the function `SK` was in the same package as the function `Second`,

https://github.com/IBM/fp-go/blob/ddafd1ee579115b0cbd71dc1a9dedc26a5f887fb/function/function.go#L64-L67

and that their definitions matched:

https://github.com/IBM/fp-go/blob/ddafd1ee579115b0cbd71dc1a9dedc26a5f887fb/function/bind.go#L29-L31

Next, I looked to see if `SK` was being used anywhere internally and did the same for `Second`. 
`SK` was [not being used in fp-go](https://github.com/search?q=repo%3AIBM%2Ffp-go+SK&type=code), but I see now that it [is used in fp-ts](https://github.com/search?q=repo%3Agcanti%2Ffp-ts+%22+SK%22&type=code) in a number of places.

Therefore, I figured that the function `Second`, with its more expressive name, I would imagine to be preferable to SK in most contexts.

However, as you mentioned, removing `SK` would stray from the parent library of fp-ts. In order to validate this choice, one might need to go through and observe the corresponding go implementations of the ts functions where SK is used. 

This is what I am trying to do now.
As an example, in the fp-ts IOEither pkg, there is a function called `traverseReadonlyNonEmptyArrayWithIndex` which uses SK. 

https://github.com/gcanti/fp-ts/blob/01b8661f2fa594d6f2010573f010d358e6808d13/src/IOEither.ts#L1129-L1132

I am looking for the equivalent fp-go function (or functions too, I suppose); but I am having trouble finding a match.

Thank you for taking the time to read this,
I look forward to hearing your thoughts!

**Comment by CarstenLeue** [comment]
Hi @a-lipson, first I'd like to say sorry for the long delay. 

On Second vs SK: I also found Second more expressive, so I added it to the library. SK is indeed there for analogy with `fp-ts`. 

on `traverseReadonlyNonEmptyArrayWithIndex`:

in the current version of the `fp-go` I do not have the concept of a `non-empty-array`. I was pondering about adding it as a specialization of the array type, since some of the operations, e.g. `head`, could have a simpler signature compared to a regular array. 

So there is no direct equivalent of `traverseReadonlyNonEmptyArrayWithIndex`. The equivalent for the general array would be `https://github.com/IBM/fp-go/blob/v1.0.28/ioeither/traverse.go#L23` but I realize that I am missing the "withIndex" versions. I'll add them, an oversight ...

**Comment by CarstenLeue** [comment]
The missing methods are part of v1.0.29

**Comment by CarstenLeue** [comment]
> on that note, do you happen to know what "SK" means?

I think it comes from https://en.wikipedia.org/wiki/SKI_combinator_calculus

**Comment by a-lipson** [comment]
> > on that note, do you happen to know what "SK" means?
> 
> I think it comes from https://en.wikipedia.org/wiki/SKI_combinator_calculus

I didn't look close enough when asking my question, but I believe that you are correct.

https://github.com/gcanti/fp-ts/blob/9f3e58111113b2e10248eca871940359f4924ac0/src/function.ts#L679-L684

**Comment by a-lipson** [comment]
I read up a little bit on SKI calculus. I saw an interesting video of someone implementing the reductions rules in Haskell, but I'm afraid that most of it went over my head. 
https://gist.github.com/mjgpy3/d0c9b4b7280b0b3d37231e6b6b2e9724

Anyways, I'm going to close this pull request. Thank you for your time and feedback, as always!

**Pull request closed without merging**
